name: Build a qmk on demand

on:
  workflow_dispatch:
    inputs:
      keyboard:
        description: 'Keyboard'
        required: true
        type: choice
        options:
        - keyball39
        - keyball44
        - keyball61
        - keyball46
        - one47
      keymap:
        description: 'Keymap'
        required: true
        type: string
        default: 'default'
      type:
        description: 'Build Type'
        required: true
        type: choice
        default: 'firmware'
        options:
        - firmware
        - keyboard.json

jobs:

  build:

    uses: ./.github/workflows/run-qmk.yml
    with:
      qmk_version: '0.22.14'
      keyboard:    ${{ inputs.keyboard }}
      keymap:      ${{ inputs.keymap }}
      type:        ${{ inputs.type }}
